
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Analizadores;

/** CUP generated class containing symbol constants. */
public class Simbolos {
  /* terminals */
  public static final int delimitador = 11;
  public static final int palabraACTION = 33;
  public static final int tipodato = 24;
  public static final int parc = 7;
  public static final int palabraROTATE = 29;
  public static final int para = 6;
  public static final int palabraR = 26;
  public static final int coma = 19;
  public static final int numero = 8;
  public static final int palabraFOR = 28;
  public static final int main = 17;
  public static final int por = 4;
  public static final int variables = 10;
  public static final int letranum = 12;
  public static final int num = 20;
  public static final int asignacion = 22;
  public static final int declaracion = 21;
  public static final int menos = 3;
  public static final int palabraMOVE_M = 32;
  public static final int corizquierdo = 14;
  public static final int div = 5;
  public static final int EOF = 0;
  public static final int letra = 9;
  public static final int palabraMOVE_H = 30;
  public static final int palabraIF = 25;
  public static final int palabraELSE = 27;
  public static final int error = 1;
  public static final int palabraMOVE_C = 31;
  public static final int comentarios = 23;
  public static final int condiciones = 18;
  public static final int mas = 2;
  public static final int begin = 13;
  public static final int corderecho = 15;
  public static final int oracion = 16;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "mas",
  "menos",
  "por",
  "div",
  "para",
  "parc",
  "numero",
  "letra",
  "variables",
  "delimitador",
  "letranum",
  "begin",
  "corizquierdo",
  "corderecho",
  "oracion",
  "main",
  "condiciones",
  "coma",
  "num",
  "declaracion",
  "asignacion",
  "comentarios",
  "tipodato",
  "palabraIF",
  "palabraR",
  "palabraELSE",
  "palabraFOR",
  "palabraROTATE",
  "palabraMOVE_H",
  "palabraMOVE_C",
  "palabraMOVE_M",
  "palabraACTION"
  };
}

